#!/usr/bin/env python3
"""
Python script to visualize b→sμμ Wilson coefficients
calculated using the HyperIso library.

This script reads the CSV file generated by the C++ example
and creates plots showing the scale dependence of the Wilson coefficients.
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import argparse
import os

def load_data(filename):
    """Load Wilson coefficients data from CSV file."""
    if not os.path.exists(filename):
        print(f"Error: File {filename} not found.")
        print("Please run the C++ example first to generate the data.")
        return None
    
    try:
        data = pd.read_csv(filename)
        print(f"Loaded data from {filename}")
        print(f"Data shape: {data.shape}")
        return data
    except Exception as e:
        print(f"Error reading file {filename}: {e}")
        return None

def plot_scale_dependence(data, save_plots=True):
    """Create plots showing scale dependence of Wilson coefficients."""
    
    # Create figure with subplots
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    fig.suptitle('b→sμμ Wilson Coefficients Scale Dependence', fontsize=16)
    
    # Plot C7
    axes[0, 0].plot(data['μ (GeV)'], data['C7_real'], 'b-', linewidth=2, label='Real')
    axes[0, 0].plot(data['μ (GeV)'], data['C7_imag'], 'r--', linewidth=2, label='Imaginary')
    axes[0, 0].set_xlabel('μ (GeV)')
    axes[0, 0].set_ylabel('C7')
    axes[0, 0].set_title('C7 Wilson Coefficient')
    axes[0, 0].legend()
    axes[0, 0].grid(True, alpha=0.3)
    
    # Plot C9
    axes[0, 1].plot(data['μ (GeV)'], data['C9_real'], 'b-', linewidth=2, label='Real')
    axes[0, 1].plot(data['μ (GeV)'], data['C9_imag'], 'r--', linewidth=2, label='Imaginary')
    axes[0, 1].set_xlabel('μ (GeV)')
    axes[0, 1].set_ylabel('C9')
    axes[0, 1].set_title('C9 Wilson Coefficient')
    axes[0, 1].legend()
    axes[0, 1].grid(True, alpha=0.3)
    
    # Plot C10
    axes[1, 0].plot(data['μ (GeV)'], data['C10_real'], 'b-', linewidth=2, label='Real')
    axes[1, 0].plot(data['μ (GeV)'], data['C10_imag'], 'r--', linewidth=2, label='Imaginary')
    axes[1, 0].set_xlabel('μ (GeV)')
    axes[1, 0].set_ylabel('C10')
    axes[1, 0].set_title('C10 Wilson Coefficient')
    axes[1, 0].legend()
    axes[1, 0].grid(True, alpha=0.3)
    
    # Plot magnitude comparison
    magnitudes = np.sqrt(data['C7_real']**2 + data['C7_imag']**2)
    axes[1, 1].plot(data['μ (GeV)'], magnitudes, 'b-', linewidth=2, label='|C7|')
    
    magnitudes = np.sqrt(data['C9_real']**2 + data['C9_imag']**2)
    axes[1, 1].plot(data['μ (GeV)'], magnitudes, 'r-', linewidth=2, label='|C9|')
    
    magnitudes = np.sqrt(data['C10_real']**2 + data['C10_imag']**2)
    axes[1, 1].plot(data['μ (GeV)'], magnitudes, 'g-', linewidth=2, label='|C10|')
    
    axes[1, 1].set_xlabel('μ (GeV)')
    axes[1, 1].set_ylabel('|C|')
    axes[1, 1].set_title('Magnitude Comparison')
    axes[1, 1].legend()
    axes[1, 1].grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    if save_plots:
        plt.savefig('wilson_coefficients_scale_dependence.png', dpi=300, bbox_inches='tight')
        print("Plot saved as 'wilson_coefficients_scale_dependence.png'")
    
    plt.show()

def plot_comparison(data_files, save_plots=True):
    """Compare Wilson coefficients from different orders (LO, NLO, NNLO)."""
    
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.suptitle('Wilson Coefficients: LO vs NLO vs NNLO Comparison', fontsize=16)
    
    colors = ['blue', 'red', 'green']
    orders = ['LO', 'NLO', 'NNLO']
    
    for i, (filename, color, order) in enumerate(zip(data_files, colors, orders)):
        if os.path.exists(filename):
            data = pd.read_csv(filename)
            mu_b = 4.2  # b-quark scale
            
            # Find closest value to mu_b
            idx = np.argmin(np.abs(data['μ (GeV)'] - mu_b))
            
            # Plot the values at mu_b
            C7_val = complex(data.iloc[idx]['C7_real'], data.iloc[idx]['C7_imag'])
            C9_val = complex(data.iloc[idx]['C9_real'], data.iloc[idx]['C9_imag'])
            C10_val = complex(data.iloc[idx]['C10_real'], data.iloc[idx]['C10_imag'])
            
            coefficients = [C7_val, C9_val, C10_val]
            names = ['C7', 'C9', 'C10']
            
            real_parts = [c.real for c in coefficients]
            imag_parts = [c.imag for c in coefficients]
            
            x = np.arange(len(names))
            width = 0.35
            
            axes[i].bar(x - width/2, real_parts, width, label='Real', color=color, alpha=0.7)
            axes[i].bar(x + width/2, imag_parts, width, label='Imaginary', color=color, alpha=0.4)
            
            axes[i].set_xlabel('Wilson Coefficient')
            axes[i].set_ylabel('Value')
            axes[i].set_title(f'{order} Order')
            axes[i].set_xticks(x)
            axes[i].set_xticklabels(names)
            axes[i].legend()
            axes[i].grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    if save_plots:
        plt.savefig('wilson_coefficients_comparison.png', dpi=300, bbox_inches='tight')
        print("Comparison plot saved as 'wilson_coefficients_comparison.png'")
    
    plt.show()

def print_summary(data):
    """Print a summary of the Wilson coefficients."""
    print("\n=== Wilson Coefficients Summary ===")
    print(f"Data range: μ = {data['μ (GeV)'].min():.1f} to {data['μ (GeV)'].max():.1f} GeV")
    print(f"Number of points: {len(data)}")
    print()
    
    # Find values at typical b-quark scale
    mu_b = 4.2
    idx = np.argmin(np.abs(data['μ (GeV)'] - mu_b))
    
    print(f"Values at μ = {data.iloc[idx]['μ (GeV)']:.1f} GeV:")
    print(f"C7:  {data.iloc[idx]['C7_real']:8.6f} + {data.iloc[idx]['C7_imag']:8.6f}i")
    print(f"C9:  {data.iloc[idx]['C9_real']:8.6f} + {data.iloc[idx]['C9_imag']:8.6f}i")
    print(f"C10: {data.iloc[idx]['C10_real']:8.6f} + {data.iloc[idx]['C10_imag']:8.6f}i")
    print()
    
    # Calculate magnitudes
    C7_mag = np.sqrt(data.iloc[idx]['C7_real']**2 + data.iloc[idx]['C7_imag']**2)
    C9_mag = np.sqrt(data.iloc[idx]['C9_real']**2 + data.iloc[idx]['C9_imag']**2)
    C10_mag = np.sqrt(data.iloc[idx]['C10_real']**2 + data.iloc[idx]['C10_imag']**2)
    
    print("Magnitudes:")
    print(f"|C7|:  {C7_mag:.6f}")
    print(f"|C9|:  {C9_mag:.6f}")
    print(f"|C10|: {C10_mag:.6f}")

def main():
    parser = argparse.ArgumentParser(description='Visualize b→sμμ Wilson coefficients')
    parser.add_argument('--file', '-f', default='wilson_coefficients_nlo.csv',
                       help='CSV file containing Wilson coefficients data')
    parser.add_argument('--no-save', action='store_true',
                       help='Do not save plots to files')
    parser.add_argument('--compare', action='store_true',
                       help='Compare different orders (requires LO, NLO, NNLO files)')
    
    args = parser.parse_args()
    
    # Load data
    data = load_data(args.file)
    if data is None:
        return
    
    # Print summary
    print_summary(data)
    
    # Create plots
    if args.compare:
        # Try to find files for different orders
        files_to_compare = [
            'wilson_coefficients_lo.csv',
            'wilson_coefficients_nlo.csv',
            'wilson_coefficients_nnlo.csv'
        ]
        
        existing_files = [f for f in files_to_compare if os.path.exists(f)]
        if len(existing_files) >= 2:
            plot_comparison(existing_files, not args.no_save)
        else:
            print("Warning: Not enough files found for comparison.")
            print("Expected files: wilson_coefficients_lo.csv, wilson_coefficients_nlo.csv, wilson_coefficients_nnlo.csv")
            plot_scale_dependence(data, not args.no_save)
    else:
        plot_scale_dependence(data, not args.no_save)

if __name__ == "__main__":
    main()